export const CONVERT_CSV_FILE = 'CONVERT_CSV_FILE',
  CONVERT_CSV_FILE_SUCCESS = 'CONVERT_CSV_FILE_SUCCESS',
  CONVERT_CSV_FILE_FAILURE = 'CONVERT_CSV_FILE_FAILURE',
  SELECT_STUDENT = 'SELECT_STUDENT';
